install:
 - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
 - sudo apt-get install chktex texlive-latex3  texlive-math-extra
language: bash
script: 
 - cd 2015-scala-symposium/
 - bash ./clean-make.sh
 - cd ../
 - cd 2014-ecoop-demo/
 - make clean
 - make
 - cd ../
notifications:
  email:
    - gvojin@gmail.com
    - denys.shabalin@epfl.ch
