install:
 - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
 - sudo apt-get install chktex texlive-latex3
language: bash
script: 
 - cd 2015-ecoop/
 - make clean
 - make
 - cd ../
 - cd 2014-ecoop-demo/
 - make clean
 - make
 - cd ../
